language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
script:
  # Run pep8 on all .py files in all subfolders
  # (I ignore "E402: module level import not at top of file"
  # because of use case sys.path.append('..'); import <module>)
  - find . -name \*.py -exec pep8 --ignore=E402 {} +
  # run tests
  - nosetests