language: python
branches:
  only: 
    - master
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y expect
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
  # Run pycodestyle on all .py files in all subfolders
  # (I ignore "E402: module level import not at top of file"
  # because of use case sys.path.append('..'); import <module>)
  - find . -name \*.py -exec pycodestyle --ignore=E402 {} +
  
  # run tests
  - |
      bash .travis/setup-ssh.sh
  - |
      bash .travis/clone-test-repo.sh
  - |
      bash .travis/test-git-cd-version.sh
  - |
      bash .travis/test-git-cd-init.sh


env:
  global:
    - secure: "P72+wz8xMFMyqIvKYI+5PSvvsBouGCpJXtEzweA0apu6ine/6lUJzDpQ+Ef+3DVBHpzKHJzAzKFG1jYXr81NsnA8beigOq2SMYHnwq0VCITUqJ1N1cmEO41aU0KVd2mkZ7F5oNA7wxzg4W9LdLggD+KHuzWeXsffSCrcBhZ7drwnvTSzxUKSflxabmjBAyMBIPVwn+xU6l0Rq5s7WkPlwLLW+PobzySw8cNlDkRLkBPsS8cO4aQeR4NEw+LRSnBODvY9fyIGcsqw9kTO2feiYfdJMMXNO1ZDN3/vR8bDThWs+sHvaG4ZlWs6QvAo8lzXi7j4p+KHirhOrjccIgO2JwYNqJ4kKVgrcFw6nFdd+ogq1hj65cL3GrNsyEfcxKwn/wXa8Q4pM6pXpKFe+CFVftQrrN4uuQQa8NMV78poRRTrkDnVlVdjj4tITMxtHVEAWHJit9fAM0jPmXHsleujTdPDLWl05uCzpx0UF+qyg2gmCSfy9syObAJVIGmU5okC95dRwzDeEi4ES7wSyDxt72oLc0mZd43qSpQqaX+jRk01n6OewMmuU3pxNYyPwj78NKYWv3EQpFw0+m4dtldXtFvuWt0SHCv60RSBscw0dvYs+wFKNdMwT2U9Pdw509Ss2pnYjEfZOpt700Wu0zNx4ERh0Bw5+dsEaDdGZVa3dH4="
