language: python
branches:
  only: 
    - master
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
  # Run pycodestyle on all .py files in all subfolders
  # (I ignore "E402: module level import not at top of file"
  # because of use case sys.path.append('..'); import <module>)
  - find . -name \*.py -exec pycodestyle --ignore=E402 {} +
  # run tests
  - nosetests